markdown: redcarpet
highlighter: pygments

title: "Hudson Brendon Blog"
description: "Full Stack Developer and Entrepreneur"

permalink: /:title/

links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Photos
    url: /photos
  - title: About me
    url: /about

url: "http://hudsonbrendon.com.br"
domain: "hudsonbrendon.com.br"
baseurl: ""

author:
    name: "Hudson Brendon"
    image: "https://avatars2.githubusercontent.com/u/5201888?v=3&s=460"
    biography: "A full stack developer and entrepreneur who likes to play with the guitar in his spare time"
    email: contato@hudsonbrendon.com.br

twitter:
    url:  https://twitter.com/hudsonbrendon
    desc: Follow me on twitter
    username: hudsonbrendon

facebook:
    url:  https://fb.com/hudsonbrendon
    desc: Connect with me facebook

github:
    url:  https://github.com/hudsonbrendon
    desc: Fork me on github

google_plus:
    url:  https://plus.google.com/116189383737787140965
    desc: Add me on google+

feedburn:
    username: hudsonbrendon

disqus:
    short_name: hudsonbrendonblog

ga: UA-25536682-6

exclude: ['package.json', 'src', 'node_modules']
