import Head from "next/head";
import fs, { read } from "fs";
import matter from "gray-matter";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  try {
    const files = fs.readdirSync("public/posts");

    const posts = files.map((fileName) => {
      const slug = fileName.replace(".md", "");
      const readFile = fs.readFileSync(`public/posts/${fileName}`, "utf-8");

      const { data: frontmatter } = matter(readFile);

      return {
        slug,
        frontmatter,
      };
    });

    return {
      props: { posts },
    };
  } catch (error) {
    console.error(error);

    return {
      props: {},
    };
  }
}

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>Lucas Miqueias</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Lucas Miqueias</h1>
        <h2>Product Designer And Front End Enthusiastic</h2>
      </header>
      <aside></aside>
      <div className={styles.container}>
        <div className="grid grid-cols-1 md:grid-cols-3 lg-grid-cols-4 md:p-0 mt-8">
          {posts.map(({ slug, frontmatter }: any) => (
            <div
              key={slug}
              className="border border-gray-200 m-2 rounded-xl shadow-lg overflow-hidden flex flex-col"
            >
              <Link href={`/post/${slug}`}>
                <h1 className="p-4 text-gray-50">{frontmatter.title}</h1>
              </Link>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
